### ISSUE TITLE
Some pictures in the Mac version show text with white edges. Can this be solved?

### ISSUE THREAD

**Issue by yshumy** [xiaoyifang/goldendict-ng#1490]
這樣，暗黑模式下：

<img width="1058" alt="截屏2024-05-02 14 32 23" src="https://github.com/xiaoyifang/goldendict-ng/assets/103359913/f89f70cd-652b-4767-8ba1-87d183f5e486">

這是原圖：

![image](https://github.com/xiaoyifang/goldendict-ng/assets/103359913/24092e38-9d72-443f-9fcc-a35eec4622ea)

**Comment by shenlebantongying** [comment]
You can add these to article-style.css or dictionary's css file.

```css
img {
  filter: grayscale(0.80) invert(0.94);
  background-color: transparent !important; 
  
or 

  background-color: white !important; 
}
```

This problem cannot be addressed generally.

https://forum.freemdict.com/t/topic/11495/3060

![image](https://github.com/xiaoyifang/goldendict-ng/assets/20123683/d6e232ac-ab33-4b20-88d4-f620d4f1d47f)
