### ISSUE TITLE
Feature request: Customize serif and sans-serif fonts

### ISSUE THREAD

**Issue by stephenmk** [xiaoyifang/goldendict-ng#947]
Most web browsers allow the user to set different serif and sans-serif fonts.

<details>
    <summary>Firefox menu</summary>
   
![firefox](https://github.com/xiaoyifang/goldendict-ng/assets/8003332/1262af76-dc84-4517-ba3a-b2feec38f5b5)
</details>

<details>
    <summary>Chromium menu</summary>
   
![chromium](https://github.com/xiaoyifang/goldendict-ng/assets/8003332/1348b5cc-fbf1-44f9-b7c3-305d435809f1)
</details>

GoldenDict-ng currently only allows the user to select one font which is applied everywhere.

<details>
    <summary>GoldenDict-ng menu</summary>
   
![goldendict](https://github.com/xiaoyifang/goldendict-ng/assets/8003332/9bea38e5-2109-4726-bfe0-ff0d643f8bb4)
</details>

So for example, elements with the following classes applied should be displayed differently depending on the fonts selected by the user.

```css
.class1 {
    font-family: sans-serif;
}

.class2 {
    font-family: serif;
}
```

**Comment by shenlebantongying** [comment]
To control fonts in a higher granularity, you may consider creating `article-style.css` in `~/.goldendict/` or `~/.config/goldendict/`.

https://xiaoyifang.github.io/goldendict-ng/topic_userstyle/

**Comment by stephenmk** [comment]
I think my issue is a little bit different.

I am designing dictionaries for use with goldendict. I could write a style class such as this:

```css
.class3 {
    font-family: "Noto Serif CJK JP", "Source Han Serif JP Medium", serif;
}
```

If the user does not have "Noto Serif CJK JP" or "Source Han Serif JP Medium" installed, the font will fallback to `serif`. But GoldenDict will not necessarily display a serif font; it will use the font chosen as the "Dictionary Font" in the settings.

I think users should be able to choose different `serif` and `sans-serif` fonts. They should not revert to the same style of font.

**Comment by xiaoyifang** [comment]
https://doc.qt.io/QT-5/qwebenginesettings.html#FontFamily-enum

This indeed can be done ,maybe in the future.

As I thought maybe too few person would find chance to use it.

**Comment by stephenmk** [comment]
I am converting Japanese dictionaries from the [Monokakido "Dictionaries" app](https://www.monokakido.jp/ja/dictionaries/app/) to the MDict format for use with GoldenDict. Many of these dictionaries use both sans-serif and serif fonts. 

For example, all of the **bold** fonts in this image are displayed in sans-serif fonts.

![fonts](https://github.com/xiaoyifang/goldendict-ng/assets/8003332/2621bbd5-1361-4af8-a973-3dcbcd849d88)

This only works if the user has one of the fonts I have defined in the stylesheet file.

```css
@font-face {
    font-family: jpgothic;
    src: local("メイリオ"), local("ヒラギノ角ゴ Pro W3"), local("Hiragino Kaku Gothic Pro"), local("Meiryo"), local("Noto Sans CJK JP"), local("IPAexGothic"), local("Source Han Sans JP"), local("ＭＳ Ｐゴシック"), local("MS Pgothic"), local("sans-serif");
}

@font-face {
    font-family: jpmincho;
    src: local("Noto Serif CJK JP"), local("IPAexMincho"), local("Source Han Serif JP"), local("MS PMincho"), local("serif");
}
```

If the user could select their preferred serif and sans-serif fonts in the GoldenDict settings, I would not need to define these font-faces.
