### ISSUE TITLE
feature: use metadata.toml to control the creation of fullindex of single dictionary

### ISSUE THREAD

**Issue by xiaoyifang** [xiaoyifang/goldendict-ng#995]
**Is your feature request related to a problem? Please describe.**
There are cases when users do not want to fullindex the dictionary to save the disk space.

**Describe the solution you'd like**

use metadata.toml and a new add field called `fullindex`,if no specified , the value default to `true` ,  this field value should be combined with goldendict's fullindex setting.

fullindex && enabled_fullindex(in the preference)

```toml
categories = [ "English", "Russian", "Chinese" ]
fullindex=false   # or 0/1 or on/off

# the following fields have not supported yet.
[metadata]
name = "New Name"
langfrom = "English"
langto = "Russian"
```

**Describe alternatives you've considered**

create a specila folder for all the dictionaries which do no need to create the fullindex .
The folder name can be ,for example ,   `nofts`.

Any dictionaries in this very folder will not  create the fullindex.

**Additional context**
